### ISSUE TITLE
Certificado A3

### ISSUE THREAD

**Issue by uilhianet** [lealhugui/node-dfe#16]
Possibilidade de Utilizar o certificado A3

**Comment by lealhugui** [comment]
Bom dia,
Tu pode explicar um pouco como é a arquitetura da tua aplicaçao? Certificados A3 normalmente sao fisicos, o que torna inviavel seu uso em um modelo cliente-servidor.

**Comment by uilhianet** [comment]
Rodando com electron

**Comment by lealhugui** [comment]
Tem algum SO especifico como target? Ou pretende liberar pra darwin/linux/win32?

Como a lib recebe um objeto de certificados, se tu pegar o objeto do certificado (ex, via windows pode-se usar a lib [win-ca](https://github.com/ukoloff/win-ca)) tu pode passar ele pra lib e deve funcionar naturalmente.

Se tu tiver alguma duvida, monta um exemplo de como tu vai usar a node-dfe que te ajudamos.

**Comment by uilhianet** [comment]
Obrigado pela dica, vou tentar utilizar essa biblioteca. Caso haver necessidade de alguma mudança faço um pull request

**Comment by lealhugui** [comment]
Perfeito! PRs são sempre bem vindas :)

**Comment by uilhianet** [comment]
Já utilizou win-ca?

**Comment by lealhugui** [comment]
Nao.

Em sex., 27 de mar. de 2020 às 14:57, uilhianet <notifications@github.com>
escreveu:

**Comment by lealhugui** [comment]
Ainda com problema?
Se nao houver mais problema, favor encerrar a Issue.

**Comment by uilhianet** [comment]
Eu não conseguir utilizar a biblioteca indicada.
