### ISSUE TITLE
Andamento do projeto.

### ISSUE THREAD

**Issue by JosiasPereira** [lealhugui/node-dfe#17]
Olá, saudações! 
Antes de mais nada, gostaria de dizer que acho muito bacana a iniciativa da lib, vai ajudar muita gente com certeza. 👏👏

Tenho interesse na lib e gostaria de saber se tem alguma previsão da liberação de emissão NFe(55). 
Também me coloca a disposição para contribuir no desenvolvimento.

**Comment by lealhugui** [comment]
Boa noite Josias!

Agradeço o elogio!
Com relação ao modelo 55, a lib deve suportar “out of the box”, uma vez que
o modelo 65 e baseado nele.
Claro, ainda existem gaps de algumas tags não preenchidas, mas o mais
importante é o teste desse modelo. Encontrando esses gaps, podemos
trabalhar juntos pra ir matando todos eles.

Em sex, 10 de abr de 2020 às 20:20, Josias Pereira <notifications@github.com>
escreveu:
