### ISSUE TITLE
Compatibilidade com SP

### ISSUE THREAD

**Issue by souzajr** [lealhugui/node-dfe#3]
Fala, pessoal! Excelente projeto, parabéns.

Notei que o projeto só é compatível com RS/PR. Rola liberar também para SP?

**Comment by lealhugui** [comment]
Opa, óbvio que rola!
Se quiser, tu mesmo pode fazer uma PR, que assim que der nós fazemos o merge; outta forma é aguardar a próxima liberação de patch (deve acontecer dentro de alguns dias).

**Comment by souzajr** [comment]
Então beleza, vou aguardar o próximo patch. Obrigadão!
