### ISSUE TITLE
README.md mais claro

### ISSUE THREAD

**Issue by jlucas577** [lealhugui/node-dfe#30]
Encontrei a biblioteca navegando pelo NPM e necessito muuuuito de uma biblioteca que gere NFC-e para o meu sistema NodeJS, porém não consegui compreender bem quais informações devem ser enviadas para realizar o procedimento de criaçao da nota fiscal, também senti falta de detalhes sobre o cert, como obter, formatos..

**Comment by lealhugui** [comment]
Perfeito @jlucas577 .
Adicionei a tag marcando essa issue como "help wanted".

**Comment by jlucas577** [comment]
Show, fico no aguardo.

**Comment by geovanentx** [comment]
> Perfeito @jlucas577 .
> Adicionei a tag marcando essa issue como "help wanted".

Da uma olhada no arquivo de teste
https://github.com/lealhugui/node-dfe/blob/master/test.js

**Comment by lealhugui** [comment]
> > Perfeito @jlucas577 .
> > Adicionei a tag marcando essa issue como "help wanted".
> 
> Da uma olhada no arquivo de teste
> https://github.com/lealhugui/node-dfe/blob/master/test.js

Desculpa @geovanentx , nao entendi a referencia.

**Comment by damianan** [comment]
@lealhugui boa tarde! tem algum test somente para consulta da nota fiscal ?

**Comment by lealhugui** [comment]
> @lealhugui boa tarde! tem algum test somente para consulta da nota fiscal ?

Boa tarde @damianan! Hoje nao temos, mas você pode fazer :)

**Comment by lealhugui** [comment]
Fechando o Issue por falta de atividade.
