### ISSUE TITLE
PDF DO DANFCE

### ISSUE THREAD

**Issue by tagorycardoso** [lealhugui/node-dfe#31]
Como vocês estão fazendo para gerar um PDF ou mesmo imprimir o DANFCE gerado por esta lib?
Eu ja possuo experiencia no dev de um fork do NfePHP. Estou migrando para o NODE.JS todos os meus serviços.

**Comment by felps-dev** [comment]
Eu utilizo o React-PDF para os comprovantes e funciona muito bem.

**Comment by lealhugui** [comment]
Acho q a maneira mais basica de fazer isso, é pegar o XML e jogar contra um HTML da Danfe.

**Comment by lealhugui** [comment]
Fechando a Issue por falta de atividade.
