### ISSUE TITLE
Dúvidas duvidosas

### ISSUE THREAD

**Issue by jmlavoier** [lealhugui/node-dfe#33]
Gostaria de colocar as várias dúvidas que me veio ao tentar utilizar essa aplicação. Minha intenção é ajudar, levantando informações para melhorarmos a documentação, e me inteirar para também poder contribuir com o projeto.

*Algumas perguntas podem ter relação à minha falta de conhecimento ao sistema de NF-e, caso seja complicado explicar, poderia apenas me direcionar aos documentos disponíveis pela SEFAZ ou ICP*

# Dúvidas

## Certificados digitais
https://github.com/lealhugui/node-dfe/blob/master/test.js#L7
1. Eu percebi que é necessário ter os arquivos `.key`, `.pem` e `.pfx`. Como são gerados esses arquivos? Existe uma maneira de gerar certificado sem a necessidade de comprar nas unidades certificadoras? 
2. De acordo com uma pesquisa que fiz, o arquivo `.pfx` é necessário somente para quem utiliza Windows, se for isso, poderia remover a importação deste arquivo se o SO for Unix por exemplo?
3. O arquivo `senha.txt` seria somente inserir a senha na primeira linha do arquivo? 

## Responsável Técnico
https://github.com/lealhugui/node-dfe/blob/master/test.js#L38
Eu li sobre essa questão da necessidade de inserir o responsável técnico, que é a empresa responsável pelo software de emissão da NF-e. Porém, precisa ser gerado uma hash para o CSRT, certo? Ou seja, quem quiser utilizar essa ferramenta, precisa de um certo tipo de autorização da SEFAZ ou algo assim?

## Sobre o arquivo de exemplo test.js
Este arquivo realmente é para teste? O que fico na dúvida é se realmente posso testar alterando este arquivo e executando-o, pois fico com receio de isto estar enviando para o ambiente de produção e não um ambiente de homologação.

# No aguardo
De inicio essas são minhas dúvidas. Acredito que assim que me responder, já fico mais inteirado para poder ajudar, pois gostei muito da iniciativa deste projeto.

**Comment by tfiliano** [comment]
Certificados digitais, só é possível adquirindo mesmo e tem que ser em nome de uma empresa habilitada para emissão de NFe ou NFCe, um certificado gerado localmente não vai funcionar, precisa comprar com uma autoridade certificadora  ( serasa, certisign, digiforte, etc.. )

O arquivo de senha é simplesmente se você for armazenar em arquivo, pode ler ele de variáveis de ambiente, fixar na mão ( nunca recomendado ) ou mesmo ler de um banco de dados..

Se atente que Responsável Técnico esta ligado a emissão de NFCe, e esse código é feito no site da UF onde vc pretende emitir o NFCe.

Importante saber a diferença entre NFCe ( nota fiscal do consumidor eletrônico ) pra esse em algumas UFs, não é obrigatório a identificação do consumidor ( CPF, etc.. ). 
Já a NFe ( Nota Fiscal eletrônica ) essa é obrigatório cadastro completo, cpf, cnpj, ie, endereço etc..


O arquivo de test.js  no final dele, tem funções isoladas comentadas, por exemplo, você pode executar com 1 delas desconectada para ver funcionando. Mas já tem uma Issue aqui para alguém ajudar em desenvolver arquivos com testes mesmo de funcionalidades etc...

Sobre seu medo, é sempre ideal estar com a documentação da SEFAZ por perto na hora de preencher o arquivo de teste, repare na propriedade "ambiente" quando eh alimentado o objeto "documento" no test.js

Respondi meu na correria aqui, se tiver mais dúvidas pode mandar

**Comment by lealhugui** [comment]
Assino embaixo do comment do @tfiliano . Certo em cada uma das afirmaçoes.
