### ISSUE TITLE
Propriedades Obrigatórias

### ISSUE THREAD

**Issue by marcianobandeira** [lealhugui/node-dfe#34]
Olá, primeiramente gostaria de parabenizar pelo projeto, parece bastante promissor.

Estou tentando realizar testes utilizando o pacote instalado via npm em um aplicativo node com typescript, contudo, notei que as interfaces Empresa, Endereco, DocumentoFiscal, etc, tem suas propriedades obrigatórias (sem ?), sendo necessário informar todas, de modo que não consigo realizar os testes.

Ainda estou iniciando com nodejs, realizando testes aqui e ali para ver seu potencial, será que estou fazendo algo errado?

**Comment by lealhugui** [comment]
As propriedades sao obrigatorias pois a documentaçao da NFe/NFCe exige o preenchimento delas. Caso tenha acontecido alguma alteraçao, ou alguma propriedade esteja divergente da documentaçao, o modo mais rapido de ter sua correçao aplicada e realizar uma PR com ela.

Sobre a parte de ser promissor.... hoje este projeto ja é utilizado em produçao por algumas empresas varejistas, que realizam a emissao de alguns milhares de documentos fiscais por dia, entao, ao meu ver ja passou do "promissor" :p

De qualquer forma, obrigado pelas palavras :)

**Comment by marcianobandeira** [comment]
bom dia amigo @lealhugui 

Não se sinta ofendido pelo promissor, eu quis dizer promissor da minha perspectiva, afinal trabalho com ACBr a uns bons anos e no momento estou entrando no mundo electron, nodejs, e esse projeto node-dfe é muito promissor pra min, da minha perspectiva.

Sobre as propriedades obrigatórias, não quis dizer com relação ao xml da NF-e, mas sim das interfaces utilizadas pelo projeto.
Veja por exemplo a imagem abaixo, o campo nome fantasia do emitente não é obrigatório, contudo, para que o código funcione é necessário que eu a informe.

![image](https://user-images.githubusercontent.com/1214521/108215258-e4159580-710f-11eb-9f42-0274580f53fb.png)

Provavelmente eu esteja fazendo algo errado, mas como disse anteriormente, ainda sou um novato quando se trata de nodejs.

Obrigado amigo,
Tenha um bom dia.

**Comment by lealhugui** [comment]
A tua logica esta completamente correta @marcianobandeira . Se tu fizer uma PR posso incluir na proxima release.

**Comment by marcianobandeira** [comment]
legal, obrigado amigo, vou fazer um levantamento aqui das propriedades e farei o PR.
