### ISSUE TITLE
Ajuda intalacao

### ISSUE THREAD

**Issue by RenatoJobs** [lealhugui/node-dfe#37]
Ola gostaria que algum pudesse ma ajudar estou com dificuldade em rodar o comando de instalação. 

[liveuser@localhost-live tf-nfe]$ npm install node-dfe                               npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.69.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> node-expat@2.3.18 install /home/liveuser/Desktop/TF/tf-nfe/node_modules/node-expat
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 5.8.15-301.fc33.x86_64
gyp ERR! command "/home/liveuser/.nvm/versions/node/v8.17.0/bin/node" "/home/liveuser/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/liveuser/Desktop/TF/tf-nfe/node_modules/node-expat
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN TF@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liveuser/.npm/_logs/2021-02-22T17_50_08_990Z-debug.log

**Comment by brucepc** [comment]
@RenatoJobs parece que você não tem o make instalado
pode executar `sudo apt install build-essential` ou pode instalar apenas o make para tentar resolver.

**Comment by lealhugui** [comment]
Fechando por falta de interaçao.
