### ISSUE TITLE
Adicionar a lib fast-xml-parser para manipular o XML

### ISSUE THREAD

**Issue by brucepc** [lealhugui/node-dfe#38]
A lib [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser) é performatica e realiza o parse de JSON <=> XML, assim como validação de schema e outros, facilitando a manipulação do dados que serão transmitidos no XML.

**Comment by lealhugui** [comment]
Nao me oponho desde que a resposta a essas 2 perguntas seja afirmativa:

1) Temos problema hoje de performance na serializaçao/desserializaçao do XML? 
2) A alteraçao devido a mudança de dependencia seria apenas na camada de serializaçao/desserializaçao (aka `xmlHelper.ts`)?

**Comment by lealhugui** [comment]
Fechando por falta de interaçao.
