### ISSUE TITLE
Erro no evento de Cancelamento

### ISSUE THREAD

**Issue by RacunaMatataIsLife** [lealhugui/node-dfe#39]
Estou usando o método de cancelamento que esta no nfetest

E me volta esse xml:

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Server did not recognize the value of HTTP Header SOAPAction: http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento.</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>

Com o erro: Server did not recognize the value of HTTP Header SOAPAction: http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento.

O que posso fazer?

**Comment by GuilhermeKayan** [comment]
Tenta usar mudar no servicos.json a action que está em recepcaoEvento para http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEventoNF, resolvi o meu assim, porem está dando:

Rejeição: Chave de Acesso Invalida (Modelo diferente de 55)

Porque estou tentando cancelar uma nota 65, e pequei o exemplo da 55

**Comment by RacunaMatataIsLife** [comment]
Troquei aqui é funcionou, estou testando na Nfe 55, e ta funcionando, não sei como te ajudar na 65, muito obrigado

**Comment by lealhugui** [comment]
@RacunaMatataIsLife fechando o Issue, pois entendo que seu problema foi resolvido. Precisando, só chamar ;)
