### ISSUE TITLE
Evento cancelar

### ISSUE THREAD

**Issue by GuilhermeKayan** [lealhugui/node-dfe#40]
Rejeição: Chave de Acesso Invalida (Modelo diferente de 55)

Estou recebendo esse aviso quando tento usar o exemplo que está na nfetest.js com uma nota 65, como faço para arrumar? para conseguir cancelar nota 65

**Comment by lealhugui** [comment]
O Evento de cancelamento que voce esta testando é o da NFCe mesmo? Pode mandar um exemplo da chamada que esta tentando realizar?

**Comment by GuilhermeKayan** [comment]
async function testeEventoCancelar() {
  const evento = {   
    chNFe: '29210324357698000165650010000080221685357400',
    dhEvento: moment().format(),
    tpEvento: '110111',
    nSeqEvento: 1,
    detEvento: {
      nProt:'135200002962850',
      xJust: 'Venda cancelada'
    }
  }
  
  const eventoProc = new lib.EventoProcessor(configuracoes);
  
  const ini = new Date();
  let result = await eventoProc.executar(evento);
  const fin = new Date();
  console.log(`${(fin.getTime() - ini.getTime())/1000}s`)
  
  result = require('util').inspect(result, false, null);
  console.log('Resultado Cancelamento NF-e: \n\n' + result);
}

**Comment by lealhugui** [comment]
Fechando por inatividade
