### ISSUE TITLE
Gerar Schema

### ISSUE THREAD

**Issue by claudioluciano** [lealhugui/node-dfe#6]
Como eu faço parar gerar o schema(XML) para o typescript ?

Estou querendo implementar o metodo NFeDistribuicaoDFe para consultar notas emitidas para um cnpj.

pelo que vi nos schemas que existem hoje no projeto são somente para o status e para a emissão da NFe

**Comment by lealhugui** [comment]
Pode converter o schema para typescript na mao, ou qualquer ferramenta
online pra isso.
Tendo os types/interfaces criadas, chamar a serialização já gera o XML de
forma automática.

Em sex, 27 de set de 2019 13:11, Claudio Luciano <notifications@github.com>
escreveu:

**Comment by lealhugui** [comment]
@claudioluciano , conseguiu fazer o que tu queria? Ainda precisa de ajuda?
Do contrario, vou encerrar a issue.

**Comment by claudioluciano** [comment]
Opa, desculpa a demora, ainda não tive tempo de tentar gerar os types/interfaces, mas se possível tu poderia explicar como tu fez para gerar os que estão no projeto hoje.
Olhando os logs do git eu vi que inicialmente estava sendo usando uma biblioteca python, mas depois foi removida.

**Comment by lealhugui** [comment]
Opa @claudioluciano , geramos os schemas na mão mesmo (na verdade apenas com regexp).

**Comment by lealhugui** [comment]
Fechando por inatividade.
