### ISSUE TITLE
Monitorar nota emitida para meu CNPJ

### ISSUE THREAD

**Issue by hermesalvesbr** [lealhugui/node-dfe#62]
Boa tarde pessoal,

Poderiam me indicar alguma lib/sdk que permita via meu certificado digital que eu monitore as notas fiscais emitidas para o meu CNPJ?

Gostaria de saber quando alguém emitir uma nota fiscal de venda para o meu cnpj. 

Pode ser em outra linguagem, não tem problemas. 

Agradeço desde já qualquer contribuição,

**Comment by lucashpmelo** [comment]
No começo desse ano eu tive que fazer a integração com a Sefaz para gerar evento de manifesto das NF-e emitidas contra um CNPJ, e para ajudar no processo, também fiz a integração com o serviço de Distribuição de DF-e, que é provavelmente o que você busca. Pra facilitar a manutenção da integração eu criei uma biblioteca e publiquei no [NPM](https://www.npmjs.com/package/node-mde), aqui tem o [repositório](https://github.com/lucashpmelo/node-mde) caso você queira ver o código.

Se tiver alguma duvida pode abrir uma issue no repositório da biblioteca que assim que eu tiver um tempo eu já respondo.

**Comment by hermesalvesbr** [comment]
Obrigado pela grande ajuda @lucashpmelo então pelo que entendi da sua documentação, eu não posso monitorar só com o cnpj e certificado do meu cnpj? Preciso do ultNSU?

**Comment by lucashpmelo** [comment]
Caso você não possua o *ultNSU* pode ser informado um *NSU* com valor zero como no exemplo, assim a consulta irá retornar os documentos eletrônicos emitidos nos últimos 3 meses junto com o próximo *ultNSU* que deve ser usado nas pesquisas posteriores.

>Caso seja informado com zero, ou com um NSU muito antigo, a consulta retornará unicamente as informações resumidas e documentos fiscais eletrônicos que tenham sido recepcionados pelo Ambiente Nacional no máximo nos últimos 3 meses.

Caso você tenha duvidas de como funciona o serviço de distribuição, consulte a **Nota Técnica 2014.002**, a biblioteca foi construída seguindo as especificações dela.

**Comment by hermesalvesbr** [comment]
Muito obrigado, vou testar ela por aqui. Um off-topic: Vi que você trabalho com o certificado do lado do node, usando o fs. Este seria o mesmo procedimento para assinar pdf(documentos comuns) com assinatura digital? Tem tempo que procuro alguma freela para fazer isto.

**Comment by lucashpmelo** [comment]
>Este seria o mesmo procedimento para assinar pdf(documentos comuns) com assinatura digital?

Provavelmente, eu utilizo o [xml-crypto](https://www.npmjs.com/package/xml-crypto) para fazer a assinatura no XML para o manifesto, mas nunca fiz algo para assinar PDFs e não conheço uma biblioteca para isso, mas provavelmente deve ter uma solução em node.

**Comment by hermesalvesbr** [comment]
Obrigado Lucas, vou fechar a issue e procurar seu contato
