### ISSUE TITLE
Essa Lib ainda funciona?

### ISSUE THREAD

**Issue by HimorriveL** [lealhugui/node-dfe#66]
estou tentando fazer o teste, porem da erro, quando eu olho o codigo, por exemplo no arquivo signature ele pede no infoProvider o valor "pem" que é retirado de certificado, porém essa variavel se quer existe

**Comment by tfiliano** [comment]
Voce chegou a ler o arquivo [nfetest.j](https://github.com/lealhugui/node-dfe/blob/master/nfetest.js) ?

**Comment by HimorriveL** [comment]
Olá amigo, obrigado pelo retorno, inicialmente eu fiz a instação pelo npm e pouco antes do meio dia percebi que lá não está atualizado, segunda feira eu vou testar e posto um retorno

**Comment by tfiliano** [comment]
Legal, da uma lida nesse aquivo de test, no final dele explica como vc pode extrair as informacoes do certificado digital.

E tem exemplos de cada principal metodo tambem.

**Comment by HimorriveL** [comment]
baixando esse projeto, funcionou de primeira, rs aqui o projeto está parado? conversei com o alan ele disse que esta reescrevendo o codigo, por acaso ele é participante daqui?

**Comment by tfiliano** [comment]
Não sei quem eh Alan.

Mas os criadores desse projeto aqui estão abertos para receber PR com
melhorias.

No passado eu contribuí com algumas coisas pra SP, pretendo ajudar mais em
breve e inclusive sugerir a emissão de outros documentos tbm.

**Comment by HimorriveL** [comment]
eu estive falando com uma pessoa ja que fez algunas alteracoes no projeto, mas por nao estar dentro, acabou deixando guardando em sua maquina, tem alguma forma de fazermos uma call para alinharmos isso ai? não gostaria de ter diversos repositórios com a mesma finalidade, tudo mundo vai trabalhar a mais sem precisar... manda um oi no whats... 17988189521
