### ISSUE TITLE
Problema com a requisição.

### ISSUE THREAD

**Issue by guilhermealek** [lealhugui/node-dfe#9]
Olá, estou tentando implementar a classe de testes para gerar uma nfce(PR), porém após fazer algumas modificações para gerar o xml da maneira necessária, o oo modulo me retorna status 200 e success true, mas não me retorna data e me diz apenas que ocorreu um erro na requisição.  Testei o arquivo xml juntamente com o certificado no nosso sistema de emissão de nota fiscal, e ele conseguiu emitir a nota gerada pelo próprio modulo, porém quando o módulo tenta enviar ele me retorna isso.

message:"Erro ao realizar requisição"
stack:"Error: Erro ao realizar requisição\n    at NFeProcessor.transmitirXml (c:\NodeJs\ComandaX Portal\v1.0 javascript\node_modules\node-dfe\lib\factory\processor\nfeProcessor.js:164:23)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
__proto__:Object {constructor: , name: "Error", message: "", …}

**Comment by lealhugui** [comment]
Tudo bem @guilhermealek ? Ainda busca ajuda com o problema?

**Comment by lealhugui** [comment]
Fechando por iniatividade.
